### ISSUE TITLE
Upgrade to click>=7.0

### ISSUE THREAD

**Issue by shivank1234** [willkg/dennis#103]
The click package should be upgraded to the latest version instead click>=6.0

**Comment by willkg** [comment]
Hi! I don't think this will have any effect. It just states that Dennis will work with any version of `click>=6.0`. 

Maybe you're trying to say that Dennis doesn't work with any version of click? If that's the case, can you be more specific about what's failing?

**Comment by shivank1234** [comment]
Hi Willkg 
Shivank here,Basically the thing is that I am working in the coala-community and to solve some technicality in the coala-bears repo we need dennis to only support click>=7.0
Thanks

**Comment by willkg** [comment]
I looked it up in coala and I think the issue you're talking about is this one:

https://github.com/coala/coala/issues/5797

The comment that suggests Dennis is a problem in that issue is incorrect and changing Dennis' requirement as you suggest won't help. 

Dennis' requirement for click is "any version greater than or equal to 6.0" and pip will consider any version of click greater than or equal to 6.0 as satisfying this dependency. If you install Dennis in a fresh virtualenv by itself, pip will install click 7.0 which is the latest version:

```
$ cd dennis
$ mkvirtualenv dennis
<dennis> $ pip install -e .
Obtaining file:///home/willkg/projects/dennis
Collecting polib>=1.0.8 (from dennis==0.9.1.dev0)
  Using cached https://files.pythonhosted.org/packages/30/a2/e407c3b00cace3d7fc8df14d364deeecfeb96044e1a317de583bc26eae58/polib-1.1.0-py2.py3-none-any.whl
Collecting click>=6 (from dennis==0.9.1.dev0)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Installing collected packages: polib, click, dennis
  Running setup.py develop for dennis
Successfully installed click-7.0 dennis polib-1.1.0
$
```

Given that, I think I don't think there's anything we need to do here.
