### ISSUE TITLE
Show word counts in status

### ISSUE THREAD

**Issue by wichert** [willkg/dennis#55]
Many (perhaps even most) translation agencies use word counts to estimate the amount of work. To support this it would be nice of dennis has an option to indicate the total number of words, and the total number of untranslated words.

For what it's worth this is the simple script I currently use to count total number of words:

```python
import sys
import polib


def count_words(msg):
    # Deal with Zope-style message ids
    if msg.comment.startswith(u'Default: '):
        txt = msg.comment[9:]
    else:
        txt = msg.msgid
    return len(txt.split())


for pot in sys.argv[1:]:
    catalog = polib.pofile(pot)
    texts = words = 0
    for msg in catalog:
        texts += 1
        words += count_words(msg)
    print '%s: %d texts with %d words' % (pot, texts, words)
```

**Comment by willkg** [comment]
Oh! That's a great idea! We should definitely do this.

**Comment by wichert** [comment]
Can you update that to handle Zope-style message ids?

**Comment by willkg** [comment]
I don't understand what you mean by "Zope-style" message ids. Can you explain that? What do they look like?

**Comment by wichert** [comment]
Zope's i18n system encourages people specify an identifier with translatable texts. For example `_('subject_hello', default=''Hello World')` in Python, or `<p i18n:translate="subject_hello">Hello Word</p>` in a template. This results in a PO entry with the identifier as text and the canonical text in a comment. In this case:

```
#. Default: Hello World
msgid "subject_hello"
msgstr ""
```

That is why the code snippet I provided checks for a comment starting with `Default:`.

**Comment by willkg** [comment]
That's not how PO files work, so I'm really puzzled as to why Zope does it that way. I bet Zope has problems with most PO tools.

I don't like the idea of having a check for "Default: " trigger a Zope style for word counting in the status command. I'm concerned that anyone who happens to have "Default: " in their translator comments will bump into this alternate word counting which would be confusing. Further, none of the other Dennis commands will work with Zope style PO files.

Maybe a better way to handle Zope style PO files is to change Dennis so that it uses a module for reading and writing PO files? If we did that, someone could implement a Zope style plugin that handles the Zope style.

That's definitely outside the scope of this bug. If you're interested in Dennis supporting Zope style, can you open up a new issue for it?
