### ISSUE TITLE
Linter doesn't assert that format characters match.

### ISSUE THREAD

**Issue by mythmon** [willkg/dennis#63]
Kitsune's "no" localization has this:

```
#: kitsune/kbadge/templates/kbadge/email/award_notification.ltxt:8
msgid "You have been awarded the %(title)s badge!"
msgstr "Du har fått utmerkelsen %(title)!"
```

The produces the error `unsupported format character '!' (0x21) at index 32`.

The linter should check that for every format `%(foo)X` string in the msgid, the corresponding format string in msgstr should have a matching value for `X`.

Or just check for and disallow things like `%(foo)!`.

**Comment by mythmon** [comment]
This hit sumo again. This time it was

```
#: kitsune/kbadge/templates/badger/badge_detail.html:9
msgid "Badge: %(badge_name)s"
msgstr "Báàjì: %àwọn(badge_name)"
```

**Comment by willkg** [comment]
I started trying to figure this out and then didn't get very far.

Looking at the second one, while the error is the same, the scenario is slightly different. Even if I did fix it before, I suspect we'd still have this this problem.

I'll spend some time on it next week.

**Comment by willkg** [comment]
I spent some more time on this today. The first issue was easy to fix--it's a variation on the existing notype rule that wasn't being handled, but should have been. That's fixed and landed.

The second one isn't strictly a notype issue because that one is really about `%(foo)` issues. It could be handled by issue #57 where we're using `%` operator for string formatting which then requires that all variables in msgid are also in msgstr--we can infer that because we're using python-format and they're named. It might be easy to tweak missingvars rule to raise an error instead of a warning if the variables are python-format ones.

Another possibility is to create a new rule where if it's python-format, then anything following a `%` needs to be a valid character.

Anyhow, I'm going to make a note in issue #57 to see if that solves this issue, too. If it doesn't, I'll spin it off into a new issue and solve it separately.
